### ISSUE TITLE
Remove the displaying background colour

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#116]
**Describe the bug**
Displayed the background colour when hovering on the "Technology" section icons.

**Expected behavior**
Existing code
```CSS
.img-tech:hover {
  border-color:rgba(36, 36, 250,0.3);
  transform: scale(1.05);
  background-color: rgba(36, 36, 250,0.1);
}
```
Change like follows
```CSS
.img-tech:hover {
  transform: scale(1.05);
}
```
**Screenshots**
![Screenshot (87)](https://user-images.githubusercontent.com/88996660/226633157-6f370cf2-babc-442b-9e36-7538b8be8330.png)

**Are you working on it?**
No
