### ISSUE TITLE
Change the arrow-up icon

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/ProSolutions#118]
**Describe the bug**
Invisible the arrow icon when the first time loading.

**Expected behavior**
You should include the icon using provided icon image.
![icons8-double-up](https://user-images.githubusercontent.com/88996660/226854036-009cea60-0162-4894-a12e-cacab49b9eba.gif)
You can download the above icon

**Screenshots**
![Screenshot (88)](https://user-images.githubusercontent.com/88996660/226851219-7bd38458-bd84-421d-b1f3-155e1bca0e0b.png)

**Additional context**
You should remove the following code lines
```HTML
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
```
```HTML
<span class="material-symbols-outlined">
            keyboard_double_arrow_up
 </span>
```
You should change the styles as follows
```CSS
.scroll-up-wrap{
  position: fixed;
  bottom: 30px;
  right: 20px;
  z-index: 100;
  cursor: pointer;
  display: none;
}
```
**Are you working on it?**
No
